SonHafta/OyunTakas/OyunTakas/Controllers/SliderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OyunTakas.Models;

namespace OyunTakas.Controllers
{
    public class SliderController : Controller
    {
        [Authorize(Roles = "yonetici1")]
        // GET: Slider
        public ActionResult Index()
        {
            using (OurDbContext db = new OurDbContext())
            {
                return View(db.gallery.ToList());
            }
            //return View();
        }

        //Add Images in slider
        [Authorize(Roles = "yonetici1")]
        public ActionResult AddImage()
        {
            return View();
        }
        [Authorize(Roles = "yonetici1")]
        [HttpPost]
        public ActionResult AddImage(HttpPostedFileBase ImagePath)
        {
            if (ImagePath != null)
            {
                
                System.Drawing.Image img = System.Drawing.Image.FromStream(ImagePath.InputStream);
                if ((img.Width != 800) || (img.Height != 356))
                {
                    ModelState.AddModelError("", "Image resolution must be 800 x 356 pixels");
                    return View();
                }

                // Upload your pic
                string pic = System.IO.Path.GetFileName(ImagePath.FileName);
                string path = System.IO.Path.Combine(Server.MapPath("~/Content/images"), pic);
                ImagePath.SaveAs(path);
                using (OurDbContext db = new OurDbContext())
                {
                    Gallery gallery = new Gallery { ImagePath = "~/Content/images/" + pic };
                    db.gallery.Add(gallery);
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "yonetici1")]
        // Delete Multiple Images
        public ActionResult DeleteImages()
        {
            using (OurDbContext db = new OurDbContext())
            {
                return View(db.gallery.ToList());
            }
        }

        [HttpPost]
        public ActionResult DeleteImages(IEnumerable<int> ImagesIDs)
        {
            using (OurDbContext db = new OurDbContext())
            {
                foreach (var id in ImagesIDs)
                {
                    var image = db.gallery.Single(s => s.ID == id);
                    string imgPath = Server.MapPath(image.ImagePath);
                    db.gallery.Remove(image);
                    if (System.IO.File.Exists(imgPath))
                        System.IO.File.Delete(imgPath);
                }
                db.SaveChanges();
            }
            return RedirectToAction("DeleteImages");
        }
    }
}

SonHafta/OyunTakas/OyunTakas/Controllers/TakasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OyunTakas.DAL;
using OyunTakas.Models;

namespace OyunTakas.Controllers
{
    public class TakasController : Controller
    {
        private OyunTakasContext db = new OyunTakasContext();
        //[Authorize(Roles = "kullanici")]
        [Authorize]
        // GET: Takas
        public ActionResult Index ()
        {
           
            return View(db.Takaslar.ToList());
        }

        // GET: Takas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Takas takas = db.Takaslar.Find(id);
            if (takas == null)
            {
                return HttpNotFound();
            }
            return View(takas);
        }
       
        // GET: Takas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Takas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public ActionResult Create([Bind(Include = "ID,OyunAd,IstenenOyun,AdSoyad,Eposta,Aciklama,Sehir")] Takas takas)
        {
            if (ModelState.IsValid)
            {
                db.Takaslar.Add(takas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(takas);
        }
        [Authorize(Roles = "yonetici1")]
        // GET: Takas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Takas takas = db.Takaslar.Find(id);
            if (takas == null)
            {
                return HttpNotFound();
            }
            return View(takas);
        }

        // POST: Takas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,OyunAd,IstenenOyun,AdSoyad,Eposta,Aciklama,Sehir")] Takas takas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(takas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(takas);
        }
        [Authorize(Roles = "yonetici1")]
        // GET: Takas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Takas takas = db.Takaslar.Find(id);
            if (takas == null)
            {
                return HttpNotFound();
            }
            return View(takas);
        }

        // POST: Takas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Takas takas = db.Takaslar.Find(id);
            db.Takaslar.Remove(takas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SonHafta/OyunTakas/OyunTakas/Views/Admin/AddImage.cshtml
@model OyunTakas.Models.Gallery
@{
    ViewBag.Title = "AddImage";
}

<h2>AddImage</h2>
@using (Html.BeginForm("AddImage", "Slider", FormMethod.Post,
                                        new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Gallery</legend>

        <div class="editor-label">
            Upload Image
        </div>
        <div class="editor-field">
            <input type="file" id="ImagePath" name="ImagePath" />
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
    <p>@Html.ActionLink("Slider Home", "Index", "Slider")</p>
}

SonHafta/OyunTakas/OyunTakas/Views/Admin/DeleteImages.cshtml
@{
    ViewBag.Title = "DeleteImages";
}

<h2>DeleteImages</h2>
@using (Html.BeginForm("DeleteImages", "Slider", FormMethod.Post))
{
    <table style="background-color:azure" border="1">
        <thead style="background-color:gray">
            <tr>
                <th>Select</th>
                <th>Image</th>
            </tr>
        </thead>
        <tbody>
            @Html.EditorForModel()
        </tbody>
    </table>
    <input type="submit" value="Delete Selected Images" />
}
<p>@Html.ActionLink("Slider Home", "Index", "Slider")</p>

SonHafta/OyunTakas/OyunTakas/Views/Admin/Index.cshtml
@model IEnumerable<OyunTakas.Models.Gallery>
@{
    ViewBag.Title = "Admin Panel";
}

<h2>Slider Ekle, Sil</h2>
<h3>
    @Html.ActionLink("Add Image", "AddImage", "Slider", new { id = "linkAddimage" }, null) |
    @Html.ActionLink("Delete Image", "DeleteImages", "Slider", new { id = "linkDeleteImage" }, null)
</h3>
@*@Html.Partial("~/Views/Shared/SliderPartial.cshtml", Model)*@
<h2>Takas Ekle, Sil</h2>
<h3>@Html.ActionLink("Takasları Görüntüle", "Index", "Takas")</h3>